global:
  scrape_interval: 5s

scrape_configs:
  # Kafka metrics removed - apache/kafka doesn't expose Prometheus metrics by default but wurstmeister/kafka did.
  # can consider switching to bitnami/kafka with JMX exporter for prometheus metrics in the future. 
  
  - job_name: 'graphql-gateway'
    static_configs:
      - targets: ['graphql-gateway:9200']

  - job_name: 'user-service'
    static_configs:
      - targets: ['users-service:9201']

  - job_name: 'order-service'
    static_configs:
      - targets: ['orders-service:9202']

  - job_name: 'product-service'
    static_configs:
      - targets: ['products-service:9203']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notifications-service:9205']

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['fastapi-recommendation-service:9204']
